import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "project_init.py"
SPEC = importlib.util.spec_from_file_location("project_init", SCRIPT)
project_init = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
sys.modules["project_init"] = project_init
SPEC.loader.exec_module(project_init)


class ProjectInitTests(unittest.TestCase):
    def make_db(self, base: Path, name: str = "db") -> Path:
        db = base / name
        db.mkdir()
        (db / "km-config.json").write_text(json.dumps({"llm_wiki_root": "."}), encoding="utf-8")
        (db / "registry").mkdir()
        for child in project_init.SEARCH_PATHS:
            (db / child).mkdir()
        (db / "docs").mkdir()
        (db / "docs" / "project-workflow.md").write_text("# Workflow\n", encoding="utf-8")
        return db

    def run_main(self, *args: str, cwd: Path | None = None) -> tuple[int, str, str]:
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        old_cwd = Path.cwd()
        from io import StringIO

        stdout = StringIO()
        stderr = StringIO()
        try:
            sys.stdout = stdout
            sys.stderr = stderr
            if cwd is not None:
                import os

                os.chdir(cwd)
            code = project_init.main(list(args))
            return code, stdout.getvalue(), stderr.getvalue()
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
            if cwd is not None:
                import os

                os.chdir(old_cwd)

    def test_preview_does_not_write_and_apply_is_idempotent(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "thesis project"

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db))
            self.assertEqual(code, 0, err)
            preview = json.loads(out)
            self.assertFalse(preview["applied"])
            self.assertIn("AGENTS.md", preview["create_files"])
            self.assertFalse(project.exists())

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 0, err)
            applied = json.loads(out)
            self.assertTrue(applied["applied"])
            self.assertEqual(applied["create_files"], [])
            self.assertTrue((project / "AGENTS.md").exists())
            self.assertTrue((project / "literature-evidence.json").exists())
            self.assertIn("Generated by export_project_bib.py", (project / "references.bib").read_text(encoding="utf-8"))
            self.assertEqual(json.loads((project / "literature-evidence.json").read_text(encoding="utf-8")), {"schema_version": 1, "records": []})

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 0, err)
            rerun = json.loads(out)
            self.assertIn("AGENTS.md", rerun["existing_files"])
            self.assertEqual(rerun["create_files"], [])

    def test_preserves_existing_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            existing = "custom status\n"
            (project / "STATUS.md").write_text(existing, encoding="utf-8")

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 0, err)
            self.assertEqual((project / "STATUS.md").read_text(encoding="utf-8"), existing)
            self.assertIn("STATUS.md", json.loads(out)["existing_files"])

    def test_relocated_db_and_optional_folder(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            relocated_db = self.make_db(base, "relocated db")
            project = base / "project elsewhere"

            code, out, err = self.run_main("--project", str(project), "--db-root", str(relocated_db), "--folder", "notes", "--apply")
            self.assertEqual(code, 0, err)
            config = json.loads((project / "project-config.json").read_text(encoding="utf-8"))
            self.assertEqual(set(config), {"schema_version", "db_root", "project_root", "search_paths"})
            self.assertEqual(config["db_root"], str(relocated_db.resolve()))
            self.assertEqual(config["project_root"], str(project.resolve()))
            self.assertEqual(config["search_paths"], ["indexes", "wiki", "cards", "sources"])
            self.assertTrue((project / "notes").is_dir())

    def test_config_json_escapes_windows_backslashes(self):
        files = project_init.planned_files(
            r"D:\Projects\Thesis",
            r"D:\Research\llm-wiki-db",
            "Thesis",
            template_dir=project_init.FALLBACK_TEMPLATE_DIR,
        )
        config = json.loads(files["project-config.json"])
        self.assertEqual(config["db_root"], r"D:\Research\llm-wiki-db")
        self.assertEqual(config["project_root"], r"D:\Projects\Thesis")

    def test_uses_templates_from_selected_db_root_when_present(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base, "custom-db")
            template_dir = db / "templates" / "phd-project"
            template_dir.mkdir(parents=True)
            for template in project_init.TEXT_TEMPLATES:
                source = project_init.FALLBACK_TEMPLATE_DIR / template
                (template_dir / template).write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
            (template_dir / "AGENTS.md").write_text("CUSTOM {{PROJECT_NAME}} {{DB_ROOT}}\n", encoding="utf-8")
            project = base / "project"

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 0, err)
            self.assertEqual((project / "AGENTS.md").read_text(encoding="utf-8"), f"CUSTOM project {db.resolve()}\n")

    def test_windows_drive_paths_resolve_portably_on_wsl(self):
        self.assertEqual(
            project_init.path_text_for_platform(r"D:\drive\research-db", platform_name="posix", wsl=True),
            "/mnt/d/drive/research-db",
        )
        with self.assertRaises(project_init.InitError):
            project_init.path_text_for_platform(r"D:\drive\research-db", platform_name="posix", wsl=False)

    def test_wsl_paths_resolve_portably_on_windows_text_layer(self):
        self.assertEqual(
            project_init.path_text_for_platform("/mnt/d/drive/research-db", platform_name="nt", wsl=False),
            r"D:\drive\research-db",
        )

    def test_paths_with_spaces_and_unicode(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base, "db root")
            project = base / "논문 project"

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 0, err)
            agents = (project / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(str(project.resolve()), agents)
            self.assertIn(str(db.resolve()), agents)

    def test_unsafe_target_inside_db_is_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = db / "projects" / "bad"

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertEqual(out, "")
            self.assertIn("must not be inside the database root", err)
            self.assertFalse(project.exists())

    def test_unsafe_target_containing_db_is_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            (base / "parent").mkdir()
            db = self.make_db(base / "parent", "db")
            project = db.parent

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertEqual(out, "")
            self.assertIn("must not contain the database root", err)

    def test_invalid_db_root_is_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = base / "not-db"
            db.mkdir()
            project = base / "project"

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertEqual(out, "")
            self.assertIn("missing km-config.json", err)

    def test_malformed_or_mismatched_existing_config_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            (project / "project-config.json").write_text("{bad json", encoding="utf-8")

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("Refusing malformed existing config", err)

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            other_db = self.make_db(base, "other-db")
            project = base / "project"
            project.mkdir()
            (project / "project-config.json").write_text(
                json.dumps(
                    {
                        "schema_version": 1,
                        "db_root": str(other_db.resolve()),
                        "project_root": str(project.resolve()),
                        "search_paths": project_init.SEARCH_PATHS,
                    }
                ),
                encoding="utf-8",
            )

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("Existing config db_root differs", err)

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            (project / "project-config.json").write_text(
                json.dumps(
                    {
                        "schema_version": 1,
                        "db_root": str(db.resolve()),
                        "project_root": str(project.resolve()),
                        "search_paths": project_init.SEARCH_PATHS,
                        "project_name": "old-extra-key",
                    }
                ),
                encoding="utf-8",
            )

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("unexpected keys", err)

    def test_existing_config_relative_paths_resolve_from_project_root(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            (project / "project-config.json").write_text(
                json.dumps(
                    {
                        "schema_version": 1,
                        "db_root": "../db",
                        "project_root": ".",
                        "search_paths": project_init.SEARCH_PATHS,
                    }
                ),
                encoding="utf-8",
            )

            code, out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply", cwd=base / "db")
            self.assertEqual(code, 0, err)
            self.assertIn("project-config.json", json.loads(out)["existing_files"])

    def test_unresolved_template_tokens_are_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            template_dir = db / "templates" / "phd-project"
            template_dir.mkdir(parents=True)
            for template in project_init.TEXT_TEMPLATES:
                source = project_init.FALLBACK_TEMPLATE_DIR / template
                (template_dir / template).write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
            (template_dir / "PROJECT.md").write_text("Bad {{UNKNOWN_TOKEN}}\n", encoding="utf-8")
            project = base / "project"

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("Unresolved template token", err)

    def test_symlink_outputs_are_refused_even_inside_project(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            outside = base / "outside"
            outside.mkdir()
            (project / "drafts").symlink_to(outside, target_is_directory=True)

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("existing symlink", err)

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            real_status = project / "real-status.md"
            real_status.write_text("status\n", encoding="utf-8")
            (project / "STATUS.md").symlink_to(real_status)

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("existing symlink", err)

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            db = self.make_db(base)
            project = base / "project"
            project.mkdir()
            (project / "STATUS.md").symlink_to(project / "missing-status.md")

            code, _out, err = self.run_main("--project", str(project), "--db-root", str(db), "--apply")
            self.assertEqual(code, 2)
            self.assertIn("existing symlink", err)


if __name__ == "__main__":
    unittest.main()
