import hashlib
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

import export_project_bib  # noqa: E402
import project_literature  # noqa: E402


def sha_tree(root: Path) -> dict[str, str]:
    hashes: dict[str, str] = {}
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        hashes[path.relative_to(root).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()
    return hashes


class ProjectLiteratureTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.base = Path(self.tmp.name)
        self.db = self.base / "db"
        self.project = self.base / "project"
        for path in (
            self.db / "registry",
            self.db / "sources",
            self.db / "cards",
            self.db / "indexes",
            self.db / "wiki",
            self.project,
        ):
            path.mkdir(parents=True)
        self.record_id = "paper:2025_Smith_Test"
        self.citation_key = "smith2025test"
        self.card_path = "cards/2025_Smith_Test.md"
        self.source_path = "sources/2025_Smith_Test.md"
        (self.db / self.card_path).write_text("# Card\n", encoding="utf-8")
        (self.db / self.source_path).write_text(
            "Intro text.\n<!-- page: 4 -->\nThe exact quotation spans\nmultiple spaces and lines.\nConclusion.",
            encoding="utf-8",
        )
        (self.db / "registry" / "works.jsonl").write_text(
            json.dumps(
                {
                    "record_id": self.record_id,
                    "citation_key": self.citation_key,
                    "paths": {"card": self.card_path.replace("/", "\\"), "source": self.source_path.replace("/", "\\")},
                    "title": "Test Article",
                }
            )
            + "\n",
            encoding="utf-8",
        )
        (self.db / "refs.bib").write_text(
            """% root bib

@comment{ignored {nested}}

@article{smith2025test,
  recordid = {paper:2025_Smith_Test},
  title = {A {Nested} Test},
  author = "Smith, A.",
}
""",
            encoding="utf-8",
        )
        (self.project / "project-config.json").write_text(
            json.dumps(
                {
                    "schema_version": 1,
                    "db_root": str(self.db),
                    "project_root": str(self.project),
                    "search_paths": ["indexes", "wiki", "cards", "sources"],
                }
            ),
            encoding="utf-8",
        )

    def tearDown(self):
        self.tmp.cleanup()

    def record(self, **overrides):
        data = {
            "record_id": self.record_id,
            "card_path": self.card_path,
            "citation_key": self.citation_key,
            "decision": "candidate",
            "decision_reason": "useful background",
            "argument_role": "context",
            "evidence": [
                {
                    "source_path": "2025_Smith_Test.md",
                    "quote": "The exact quotation spans multiple spaces and lines.",
                    "locator": "",
                    "verification": "source_text",
                    "interpretation": "Shows normalized exact quote matching.",
                }
            ],
            "unknowns": [],
            "reference": "Smith (2025). Test Article.",
        }
        data.update(overrides)
        return data

    def write_input(self, data):
        path = self.base / "input.json"
        path.write_text(json.dumps(data), encoding="utf-8")
        return path

    def test_upsert_validates_exact_source_and_renders_packet(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record(decision="selected"))), True)
        ledger = json.loads((self.project / "literature-evidence.json").read_text(encoding="utf-8"))
        self.assertEqual(ledger["schema_version"], 1)
        self.assertEqual(ledger["records"][0]["decision"], "selected")
        self.assertEqual(ledger["records"][0]["evidence"][0]["source_path"], self.source_path)

        report = (self.project / "literature-evidence.md").read_text(encoding="utf-8")
        self.assertIn("Generated by scripts/project_literature.py", report)
        self.assertIn(f"Card path: `{self.card_path}`", report)
        self.assertIn(f"`{self.source_path}`", report)
        self.assertIn("## References", report)
        self.assertIn("Smith (2025)", report)

        project_literature.packet(str(self.project), self.record_id)
        packets = list((self.project / "citation-packets").glob("*.md"))
        self.assertEqual(len(packets), 1)
        self.assertIn("source_text", packets[0].read_text(encoding="utf-8"))

    def test_candidate_packet_is_allowed_but_marked_not_adopted(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record())), False)
        project_literature.packet(str(self.project), self.record_id)
        packet = next((self.project / "citation-packets").glob("*.md")).read_text(encoding="utf-8")
        self.assertIn("Selection status: not adopted", packet)

    def test_missing_record_or_key_rejected_without_partial_write(self):
        before = sha_tree(self.db)
        bad = self.record(record_id="paper:missing")
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(bad)), False)
        self.assertFalse((self.project / "literature-evidence.json").exists())
        self.assertEqual(before, sha_tree(self.db))

        bad_key = self.record(citation_key="wrong")
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(bad_key)), False)
        self.assertFalse((self.project / "literature-evidence.json").exists())

    def test_wrong_source_path_and_traversal_rejected(self):
        bad = self.record(evidence=[{**self.record()["evidence"][0], "source_path": "../refs.bib"}])
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(bad)), False)

    def test_page_verified_requires_matching_page_marker(self):
        good_evidence = {**self.record()["evidence"][0], "verification": "page_verified", "locator": "4"}
        project_literature.upsert(str(self.project), str(self.write_input(self.record(evidence=[good_evidence]))), False)

        bad_evidence = {**self.record()["evidence"][0], "verification": "page_verified", "locator": "99"}
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(self.record(evidence=[bad_evidence]))), False)

    def test_selected_guard_requires_explicit_approval(self):
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(self.record(decision="selected"))), False)

    def test_duplicate_ledger_and_input_ids_or_keys_rejected(self):
        duplicate_ledger = {
            "schema_version": 1,
            "records": [self.record(), self.record()],
        }
        (self.project / "literature-evidence.json").write_text(json.dumps(duplicate_ledger), encoding="utf-8")
        with self.assertRaises(project_literature.ValidationError):
            project_literature.validate_project(str(self.project))

        (self.project / "literature-evidence.json").unlink()
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input([self.record(), self.record()])), False)

    def test_config_rejects_nested_project_and_non_exact_search_paths(self):
        nested_project = self.db / "projects" / "nested"
        nested_project.mkdir(parents=True)
        (nested_project / "project-config.json").write_text(
            json.dumps(
                {
                    "schema_version": 1,
                    "db_root": str(self.db),
                    "project_root": str(nested_project),
                    "search_paths": ["indexes", "wiki", "cards", "sources"],
                }
            ),
            encoding="utf-8",
        )
        with self.assertRaises(project_literature.ValidationError):
            project_literature.validate_project(str(nested_project))

        config_path = self.project / "project-config.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        config["search_paths"] = ["sources", "cards", "wiki", "indexes"]
        config_path.write_text(json.dumps(config), encoding="utf-8")
        with self.assertRaises(project_literature.ValidationError):
            project_literature.validate_project(str(self.project))

    def test_output_symlink_rejected_before_mutation(self):
        if not hasattr(os, "symlink"):
            self.skipTest("symlink unavailable")
        outside = self.base / "outside-status.md"
        outside.write_text("outside", encoding="utf-8")
        (self.project / "STATUS.md").symlink_to(outside)
        with self.assertRaises(project_literature.ValidationError):
            project_literature.upsert(str(self.project), str(self.write_input(self.record())), False)
        self.assertFalse((self.project / "literature-evidence.json").exists())
        self.assertEqual("outside", outside.read_text(encoding="utf-8"))

    def test_portable_windows_drive_path_maps_to_wsl_mount(self):
        if os.name == "nt":
            self.skipTest("WSL drive mapping is only expected off Windows")
        self.assertEqual(project_literature.portable_path("D:/OneDrive/demo"), Path("/mnt/d/OneDrive/demo"))
        self.assertEqual(
            project_literature.portable_path_text("/mnt/d/OneDrive/demo", kind="windows"),
            "D:/OneDrive/demo",
        )
        with self.assertRaises(project_literature.ValidationError):
            project_literature.portable_path_text("D:/OneDrive/demo", kind="posix")
        with self.assertRaises(project_literature.ValidationError):
            project_literature.portable_path_text("/mnt/d/OneDrive/demo", kind="posix")

    def test_validate_is_read_only_and_does_not_log(self):
        before = sha_tree(self.project)
        project_literature.validate_cmd(str(self.project))
        self.assertEqual(before, sha_tree(self.project))

    def test_bibliography_export_is_idempotent_and_handles_nested_entries(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record(decision="selected"))), True)
        first = export_project_bib.export_project_bib(str(self.project)).read_text(encoding="utf-8")
        second = export_project_bib.export_project_bib(str(self.project)).read_text(encoding="utf-8")
        self.assertEqual(first, second)
        self.assertIn("title = {A {Nested} Test}", first)
        self.assertNotIn("@comment", first)

    def test_empty_selected_writes_comment_bibliography(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record())), False)
        path = export_project_bib.export_project_bib(str(self.project))
        self.assertIn("No selected", path.read_text(encoding="utf-8"))

    def test_bibliography_errors_leave_no_partial_output(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record(decision="selected"))), True)
        (self.project / "references.bib").write_text("keep me", encoding="utf-8")
        (self.db / "refs.bib").write_text("@article{other,\n  title = {Other},\n}\n", encoding="utf-8")
        with self.assertRaises(project_literature.ValidationError):
            export_project_bib.export_project_bib(str(self.project))
        self.assertEqual("keep me", (self.project / "references.bib").read_text(encoding="utf-8"))

    def test_duplicate_root_bib_keys_rejected(self):
        project_literature.upsert(str(self.project), str(self.write_input(self.record(decision="selected"))), True)
        (self.db / "refs.bib").write_text(
            "@article{smith2025test, title={One}}\n@book{smith2025test, title={Two}}\n",
            encoding="utf-8",
        )
        with self.assertRaises(project_literature.ValidationError):
            export_project_bib.export_project_bib(str(self.project))

    def test_cli_validate_subprocess(self):
        result = subprocess.run(
            [sys.executable, str(SCRIPTS / "project_literature.py"), "--project", str(self.project), "validate"],
            text=True,
            capture_output=True,
            check=True,
        )
        self.assertIn('"ledger_records": 0', result.stdout)


if __name__ == "__main__":
    unittest.main()
