from __future__ import annotations

import argparse
import re
from pathlib import Path

from llm_wiki_common import add_root_arg, iter_cards, read_yaml_md


def entry_type(data: dict) -> str:
    source_type = data.get("citation_info", {}).get("source_type", "journal")
    mapping = {"book": "book", "book_chapter": "incollection", "conference": "inproceedings", "journal": "article"}
    return mapping.get(source_type, "article")


def bib_escape(value: object) -> str:
    text = "" if value is None else str(value)
    return text.replace("{", "\\{").replace("}", "\\}")


def authors_to_bib(authors: object) -> str:
    if isinstance(authors, list):
        return " and ".join(str(a) for a in authors if str(a).strip())
    return str(authors or "")


def card_to_entry(card: Path) -> tuple[str, str, str]:
    data, _ = read_yaml_md(card)
    key = data.get("citation_key") or data.get("stem") or card.stem
    record_id = data.get("record_id") or f"paper:{card.stem}"
    info = data.get("citation_info", {}) or {}
    fields = {
        "title": data.get("title", ""),
        "author": authors_to_bib(data.get("authors", [])),
        "year": data.get("year", ""),
        "doi": data.get("doi", ""),
        "url": data.get("url", ""),
        "journal": info.get("source_title", ""),
        "volume": info.get("volume", ""),
        "number": info.get("issue", ""),
        "pages": info.get("pages", ""),
        "publisher": info.get("publisher", ""),
    }
    body = [f"@{entry_type(data)}{{{key},"]
    body.append(f"  recordid = {{{bib_escape(record_id)}}},")
    for name, value in fields.items():
        if str(value).strip():
            body.append(f"  {name} = {{{bib_escape(value)}}},")
    body.append("}")
    return record_id, key, "\n".join(body)


def split_bib_entries(text: str) -> list[str]:
    if not text.strip():
        return []
    starts = [m.start() for m in re.finditer(r"(?m)^@", text)]
    if not starts:
        return [text.strip()]
    entries = []
    for i, start in enumerate(starts):
        end = starts[i + 1] if i + 1 < len(starts) else len(text)
        entries.append(text[start:end].strip())
    return entries


def entry_record_id(entry: str) -> str | None:
    m = re.search(r"(?mi)^\s*recordid\s*=\s*[{\"]([^}\"]+)", entry)
    return m.group(1).strip() if m else None


def export_refs(root: Path, record_ids: set[str] | None = None, status: str | None = None) -> Path:
    generated: dict[str, str] = {}
    ordered_ids: list[str] = []
    for card in iter_cards(root):
        data, _ = read_yaml_md(card)
        if status and data.get("metadata_status", "open") != status:
            continue
        record_id, _key, entry = card_to_entry(card)
        if record_ids and record_id not in record_ids:
            continue
        generated[record_id] = entry
        ordered_ids.append(record_id)
    bib_path = root / "refs.bib"
    if record_ids and bib_path.exists():
        existing = split_bib_entries(bib_path.read_text(encoding="utf-8"))
        seen: set[str] = set()
        merged: list[str] = []
        for entry in existing:
            rid = entry_record_id(entry)
            if rid in generated:
                merged.append(generated[rid])
                seen.add(rid)
            else:
                merged.append(entry)
        for rid in ordered_ids:
            if rid not in seen:
                merged.append(generated[rid])
        content = "% Generated by llm-wiki. Do not edit manually.\n\n" + "\n\n".join(merged).strip() + "\n"
    else:
        entries = [generated[rid] for rid in ordered_ids]
        content = "% Generated by llm-wiki. Do not edit manually.\n\n" + "\n\n".join(entries).strip() + ("\n" if entries else "")
    bib_path.write_text(content, encoding="utf-8")
    return bib_path


def main() -> int:
    parser = argparse.ArgumentParser()
    add_root_arg(parser)
    parser.add_argument("--record-id", action="append", default=None)
    parser.add_argument("--status", choices=["open", "locked"], default=None)
    args = parser.parse_args()
    root = Path(args.root).resolve() if args.root else Path.cwd().resolve()
    path = export_refs(root, set(args.record_id) if args.record_id else None, args.status)
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

