#!/usr/bin/env python3
"""Initialize a bounded PhD project workspace backed by this llm-wiki DB."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1
SEARCH_PATHS = ["indexes", "wiki", "cards", "sources"]
SCRIPT_PATH = Path(__file__).resolve()
DB_ROOT_DEFAULT = SCRIPT_PATH.parents[1]
FALLBACK_TEMPLATE_DIR = DB_ROOT_DEFAULT / "templates" / "phd-project"

TEXT_TEMPLATES = [
    "AGENTS.md",
    "PROJECT.md",
    "STATUS.md",
    "literature-evidence.md",
    "citation-gaps.md",
    "CLAUDE.md",
    "GEMINI.md",
]
CONFIG_FILE = "project-config.json"
REQUIRED_DIRS = ["citation-packets", "drafts", "outlines"]
SKELETON_LITERATURE = {"schema_version": SCHEMA_VERSION, "records": []}
EMPTY_REFERENCES_BIB = "% Generated by export_project_bib.py from project-config.json and literature-evidence.json.\n% No selected references yet.\n"


class InitError(RuntimeError):
    """User-facing initialization failure."""


def running_under_wsl() -> bool:
    if os.environ.get("WSL_DISTRO_NAME") or os.environ.get("WSL_INTEROP"):
        return True
    try:
        return "microsoft" in Path("/proc/version").read_text(encoding="utf-8").lower()
    except OSError:
        return False


def path_text_for_platform(raw: str | Path, platform_name: str | None = None, wsl: bool | None = None) -> str:
    """Convert only cross-surface path text; leave resolution to pathlib."""
    text = os.fspath(raw)
    platform = platform_name or os.name
    wsl_enabled = running_under_wsl() if wsl is None else wsl

    mnt_match = re.match(r"^/mnt/([A-Za-z])(?:/(.*))?$", text)
    if platform == "nt" and mnt_match:
        drive = mnt_match.group(1).upper()
        rest = (mnt_match.group(2) or "").replace("/", "\\")
        return f"{drive}:\\" + rest if rest else f"{drive}:\\"

    drive_match = re.match(r"^([A-Za-z]):[\\/](.*)$", text)
    if platform != "nt" and drive_match:
        if not wsl_enabled:
            raise InitError("Windows drive paths require WSL or an explicit platform mapping")
        drive = drive_match.group(1).lower()
        rest = drive_match.group(2).replace("\\", "/")
        return str(Path("/mnt") / drive / rest)

    return text


def portable_resolve(raw: str | Path, base: Path | None = None) -> Path:
    """Resolve POSIX paths and common Windows drive paths from WSL/Linux."""
    text = path_text_for_platform(raw)
    path = Path(text).expanduser()
    if not path.is_absolute():
        path = (base or Path.cwd()) / path
    return path.resolve()


def is_relative_to(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def require_not_inside_db(project_root: Path, db_root: Path) -> None:
    if project_root == db_root or is_relative_to(project_root, db_root):
        raise InitError(f"Project target must not be inside the database root: {project_root}")
    if is_relative_to(db_root, project_root):
        raise InitError(f"Project target must not contain the database root: {project_root}")


def safe_child(project_root: Path, relative: str) -> Path:
    if Path(relative).is_absolute() or ".." in Path(relative).parts:
        raise InitError(f"Unsafe relative path in initializer: {relative}")
    target = project_root / relative
    parent = target.parent
    if parent.is_symlink():
        raise InitError(f"Refusing parent path that is a symlink: {relative}")
    if parent.exists() and not is_relative_to(parent.resolve(), project_root):
        raise InitError(f"Refusing path that escapes project root through a symlink: {relative}")
    if target.is_symlink():
        raise InitError(f"Refusing existing symlink at required output path: {relative}")
    if not target.exists():
        try:
            target.lstat()
        except FileNotFoundError:
            return target
        raise InitError(f"Refusing broken or unsupported existing path: {relative}")
    if not is_relative_to(target.resolve(), project_root):
        raise InitError(f"Refusing existing path that escapes project root through a symlink: {relative}")
    return target


def load_existing_config(config_path: Path) -> dict[str, Any] | None:
    if not config_path.exists():
        return None
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise InitError(f"Refusing malformed existing config: {config_path}: {exc}") from exc
    if not isinstance(data, dict):
        raise InitError(f"Refusing malformed existing config: {config_path}: expected object")
    expected_keys = {"schema_version", "db_root", "project_root", "search_paths"}
    if set(data) != expected_keys:
        raise InitError(f"Refusing existing config with unexpected keys: {sorted(set(data) - expected_keys)}")
    if data.get("schema_version") != SCHEMA_VERSION:
        raise InitError(f"Refusing existing config with unsupported schema_version: {data.get('schema_version')!r}")
    if not isinstance(data.get("db_root"), str) or not isinstance(data.get("project_root"), str):
        raise InitError("Refusing existing config without string db_root and project_root")
    if data.get("search_paths") != SEARCH_PATHS:
        raise InitError("Refusing existing config with mismatched search_paths")
    return data


def validate_db_root(db_root: Path) -> None:
    if not db_root.exists() or not db_root.is_dir():
        raise InitError(f"Database root does not exist or is not a directory: {db_root}")
    if not (db_root / "km-config.json").is_file():
        raise InitError(f"Database root is missing km-config.json: {db_root}")
    if not (db_root / "registry").is_dir():
        raise InitError(f"Database root is missing registry/: {db_root}")


def validate_existing_config(data: dict[str, Any], db_root: Path, project_root: Path, config_base: Path) -> None:
    existing_db = portable_resolve(data["db_root"], config_base)
    existing_project = portable_resolve(data["project_root"], config_base)
    if existing_db != db_root:
        raise InitError(f"Existing config db_root differs: {existing_db} != {db_root}")
    if existing_project != project_root:
        raise InitError(f"Existing config project_root differs: {existing_project} != {project_root}")


def template_dir_for(db_root: Path) -> Path:
    db_template_dir = db_root / "templates" / "phd-project"
    if db_template_dir.is_dir():
        return db_template_dir
    return FALLBACK_TEMPLATE_DIR


def render_template(name: str, values: dict[str, str], template_dir: Path) -> str:
    path = template_dir / name
    text = path.read_text(encoding="utf-8")
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)
    if "{{" in text or "}}" in text:
        raise InitError(f"Unresolved template token in {path}")
    return text


def config_json(project_root: Path | str, db_root: Path | str) -> str:
    config = {
        "schema_version": SCHEMA_VERSION,
        "db_root": str(db_root),
        "project_root": str(project_root),
        "search_paths": SEARCH_PATHS,
    }
    return json.dumps(config, indent=2, ensure_ascii=False) + "\n"


def planned_files(project_root: Path | str, db_root: Path | str, project_name: str, template_dir: Path | None = None) -> dict[str, str]:
    values = {
        "DB_ROOT": str(db_root),
        "PROJECT_ROOT": str(project_root),
        "PROJECT_NAME": project_name,
    }
    chosen_template_dir = template_dir or template_dir_for(Path(db_root))
    files = {name: render_template(name, values, chosen_template_dir) for name in TEXT_TEMPLATES}
    files[CONFIG_FILE] = config_json(project_root, db_root)
    files["literature-evidence.json"] = json.dumps(SKELETON_LITERATURE, indent=2, ensure_ascii=False) + "\n"
    files["references.bib"] = EMPTY_REFERENCES_BIB
    return files


def build_plan(project_root: Path, db_root: Path, folders: list[str]) -> dict[str, Any]:
    config_path = safe_child(project_root, CONFIG_FILE)
    existing_config = load_existing_config(config_path)
    if existing_config:
        validate_existing_config(existing_config, db_root, project_root, config_path.parent)

    project_name = project_root.name
    files = planned_files(project_root, db_root, project_name)
    dirs = [*REQUIRED_DIRS, *folders]
    seen_dirs: list[str] = []
    for folder in dirs:
        if folder not in seen_dirs:
            seen_dirs.append(folder)

    create_files: list[str] = []
    existing_files: list[str] = []
    for relative in files:
        target = safe_child(project_root, relative)
        if target.exists():
            if not target.is_file():
                raise InitError(f"Required file path exists but is not a file: {relative}")
            existing_files.append(relative)
        else:
            create_files.append(relative)

    create_dirs: list[str] = []
    existing_dirs: list[str] = []
    for relative in seen_dirs:
        target = safe_child(project_root, relative)
        if target.exists():
            if not target.is_dir():
                raise InitError(f"Required directory path exists but is not a directory: {relative}")
            existing_dirs.append(relative)
        else:
            create_dirs.append(relative)

    return {
        "schema_version": SCHEMA_VERSION,
        "db_root": str(db_root),
        "project_root": str(project_root),
        "project_name": project_name,
        "search_paths": SEARCH_PATHS,
        "create_files": create_files,
        "existing_files": existing_files,
        "create_dirs": create_dirs,
        "existing_dirs": existing_dirs,
    }


def apply_plan(project_root: Path, db_root: Path, folders: list[str]) -> dict[str, Any]:
    plan = build_plan(project_root, db_root, folders)
    if project_root.is_symlink():
        raise InitError(f"Refusing project root symlink: {project_root}")
    project_root.mkdir(parents=True, exist_ok=True)
    if not is_relative_to(project_root.resolve(), project_root):
        raise InitError(f"Project root resolution changed unexpectedly: {project_root}")

    for relative in plan["create_dirs"]:
        target = safe_child(project_root, relative)
        target.mkdir(parents=True, exist_ok=False)

    project_name = plan["project_name"]
    files = planned_files(project_root, db_root, project_name)
    for relative in plan["create_files"]:
        target = safe_child(project_root, relative)
        target.parent.mkdir(parents=True, exist_ok=True)
        try:
            with target.open("x", encoding="utf-8") as handle:
                handle.write(files[relative])
        except FileExistsError:
            raise InitError(f"Refusing to overwrite existing file: {relative}") from None

    return build_plan(project_root, db_root, folders)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=".", help="Project directory to initialize; defaults to cwd.")
    parser.add_argument("--db-root", default=str(DB_ROOT_DEFAULT), help="llm-wiki database root; defaults to script parent.parent.")
    parser.add_argument("--folder", action="append", default=[], help="Additional project folder to create. May be repeated.")
    parser.add_argument("--apply", action="store_true", help="Create files and directories. Without this, print preview JSON only.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        cwd = Path.cwd().resolve()
        project_root = portable_resolve(args.project, cwd)
        db_root = portable_resolve(args.db_root, cwd)
        validate_db_root(db_root)
        require_not_inside_db(project_root, db_root)
        if args.apply:
            plan = apply_plan(project_root, db_root, args.folder)
            plan["applied"] = True
        else:
            plan = build_plan(project_root, db_root, args.folder)
            plan["applied"] = False
        print(json.dumps(plan, indent=2, ensure_ascii=False))
        return 0
    except InitError as exc:
        print(f"project_init: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
